spring.datasource.url=${DB_URL:jdbc:mysql://mysql-e83c992-santadip-464d.d.aivencloud.com:18507/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_Pz8a-LRDVQydQdGsO2-}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}